[app]
name = "Call Analytics System"
version = "1.0.0"
debug = false
theme = "dark"

[paths]
data = "data"
models = "models"
logs = "logs"
exports = "data/exports"
temp = "temp"

[limits]
max_file_size_mb = 100
max_batch_size = 1000
max_concurrent_jobs = 5
