[whisper]
enabled = true
model_size = "small"
device = "cpu"
compute_type = "int8"
language = "en"

[embeddings]
provider = "sentence_transformers"
model = "all-MiniLM-L6-v2"
dimension = 384
batch_size = 32

[llm]
provider = "ollama"
model = "llama3:8b"
temperature = 0.7
max_tokens = 256
timeout_seconds = 120
