[vectorstore]
provider = "chromadb"
persist_dir = "data/vectorstore"
collection_name = "call_transcripts"
distance_metric = "cosine"

[vectorstore.embeddings]
provider = "sentence-transformers"
model_name = "all-MiniLM-L6-v2"
dimension = 384
normalize = true
batch_size = 64

[ui.colors]
connected = "#16A34A"
disconnected = "#9CA3AF"
inquiry = "#3B82F6"
billing_sales = "#14B8A6"
support = "#F59E0B"
complaint = "#EF4444"
resolved = "#16A34A"
callback = "#8B5CF6"
refund = "#F59E0B"
sale_close = "#14B8A6"
unknown = "#6B7280"